### ISSUE TITLE
Multi-color select until we have support for different menus when multi-select occurs

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileexplorer#67]
Cloud commander uses one menu for both multi-select and single select. When the menu displays, there is always one item selected that is considered the "current item" and this is given different styling in the original cloud commander.
1. Actions in the menu such as "View", "Edit", "Rename" etc. that would work with only a single file work on the "current file"
2. Actions that could work with multiple files, such as "Delete" and "Pack" and "Download" work on all of the selected files.

This is confusing and there is no comparable complexity in the selection ux of finders in Windows, OS X, Gnome, etc. In all of those, you only have 1 selected file or many selected files.

Until we can cleanly support separate menus for multiple select and single select, however, we should re-add back multiple styles so we can distinguish which is the "current file".

Using oh-tech colors with the purple being the alternate:

``` css
.selected-file {
    background-color: rgb(71,10,104);
}

.selected-file.current-file {
    background-color: rgb(0, 136, 204);
}
```

![screen shot 2016-05-10 at 3 51 38 pm](https://cloud.githubusercontent.com/assets/512333/15160378/50f62af0-16c7-11e6-82d3-6a7ed54e1b41.png)

Using 20% lighter blue for the alternate:

``` css
.selected-file {
    background-color: #33bbff;
}

.selected-file.current-file {
    background-color: rgb(0, 136, 204);
}
```

![screen shot 2016-05-10 at 3 45 36 pm](https://cloud.githubusercontent.com/assets/512333/15160387/5805abf4-16c7-11e6-89b7-54b61e24c8be.png)
